### ISSUE TITLE
We have followed the steps but could not reproduce the game

### ISSUE THREAD

**Issue by ferschubert** [VMathivet/deeplens-asl-game#1]
Hello, we have followed your steps and the AWS documentation, model was deployed successfully but the game interface did not load the camera, web interface is up but no camera.

**Comment by TheWitcherish** [comment]
Hello and **thank you for using our stack!**

the web interface is connecting to the web socket server hosted on your AWS DeepLens device on port 8080 (see [row 184 of the Main.vue component](https://github.com/VMathivet/deeplens-asl-game/blob/master/src/components/Main.vue))

If the camera images are not being displayed by the web interface, it means your Lambda function (which is starting the Web Socket server) has not succeeded in this task.

Does the 1st blue led in front of your AWS DeepLens turned on? Could you kindly check logs within greengrass and more precisely, the path where your Lambda function has been deployed in order to get more details?

In addition, you can make sure your DeepLens is well-streaming the output by following that [AWS documentation](https://docs.aws.amazon.com/deeplens/latest/dg/deeplens-viewing-output.html)
It is truly helpful!

Hope it helps,
Let me know!
